#!/usr/bin/env python3
"""research_sources_index.py -- catalogues every external source already cited
across research/*.md, so a new Researcher dispatch can check what's already
been found before spending a WebSearch/WebFetch call re-finding it.

Deterministic, dependency-free, stdlib-only (same convention as
commit_diff_reread.py / research_authenticity_check.py). Scans every
research/*.md file for markdown-style links whose target is an http(s) URL
(`[text](url)`), the citation convention every existing research file already
uses. Groups by URL, records every research file that cites it (a URL cited
in more than one file is real signal that it's a load-bearing source, not
noise), and writes a single sorted index.

Usage:
    python3 research_sources_index.py <research_dir> [--out <path>]

Exit codes: 0 always (this is a read-only reporting tool, nothing to fail on
except a genuinely missing/unreadable research_dir, which exits 2).
"""
import os
import re
import sys
from urllib.parse import urlparse

LINK_RE = re.compile(r'\[([^\]]*)\]\((https?://[^)\s]+)\)')


def collect_sources(research_dir):
    """Return {url: {"texts": set(), "files": set()}} across every .md file
    directly inside research_dir (non-recursive -- matches how research/ is
    actually laid out, flat, today)."""
    sources = {}
    for name in sorted(os.listdir(research_dir)):
        if not name.endswith(".md"):
            continue
        path = os.path.join(research_dir, name)
        try:
            text = open(path, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        for m in LINK_RE.finditer(text):
            link_text, url = m.group(1).strip(), m.group(2).strip()
            entry = sources.setdefault(url, {"texts": set(), "files": set()})
            if link_text:
                entry["texts"].add(link_text)
            entry["files"].add(name)
    return sources


def render_index(sources):
    """Sort by domain then path, so sources from the same site cluster
    together -- easiest shape for a human or an agent to scan for
    'have I already found something on this domain/topic.'"""
    def sort_key(item):
        url = item[0]
        p = urlparse(url)
        return (p.netloc, p.path, url)

    lines = [
        "# Research sources index",
        "",
        "Generated by `loop-team/harness/research_sources_index.py` --"
        " every external URL already cited across `research/*.md`. Check"
        " here BEFORE dispatching a new Researcher WebSearch/WebFetch on a"
        " topic, to see whether a source has already been found (and by"
        " which research file) rather than re-discovering it blind.",
        "",
        "Regenerate after adding a new research file:"
        " `python3 loop-team/harness/research_sources_index.py research/`",
        "",
    ]
    for url, entry in sorted(sources.items(), key=sort_key):
        texts = ", ".join(sorted(entry["texts"])) or "(no link text)"
        files = ", ".join(sorted(entry["files"]))
        lines.append("- [%s](%s) -- cited in: %s" % (texts, url, files))
    lines.append("")
    return "\n".join(lines)


def main(argv):
    if not argv:
        sys.stderr.write("usage: research_sources_index.py <research_dir> [--out <path>]\n")
        return 2
    research_dir = argv[0]
    if not os.path.isdir(research_dir):
        sys.stderr.write("error: not a directory: %s\n" % research_dir)
        return 2
    out_path = None
    if "--out" in argv:
        idx = argv.index("--out")
        if idx + 1 >= len(argv):
            sys.stderr.write("error: --out requires a value\n")
            return 2
        out_path = argv[idx + 1]

    sources = collect_sources(research_dir)
    index_text = render_index(sources)

    if out_path:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(index_text)
        sys.stderr.write("wrote %d unique sources to %s\n" % (len(sources), out_path))
    else:
        print(index_text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
